function BCCT_CaSCN_MAP_GUI
D.fig = figure('Name','Causal network of Structural Covaraince Connectivity(Seed to Whole Brain, volume-based)',...       
    'units','normalized',...      
    'menubar','none',...       
    'numbertitle','off',...      
    'color',[0.95 0.95 0.95],...
    'position',[0.20 0.15 0.5 0.5]);
movegui(D.fig,'center'); 


D.OutputText = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.05,0.9,0.1,0.08],...
    'style','text',...
    'string',{'Output','Directory'},...
    'Fontsize',10);
D.OutputEDIT = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.15,0.9,0.7,0.08],...
    'style','edit',...
    'string','NULL');
D.OutputSel = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.86,0.9,0.09,0.08],...
    'style','pushbutton',...
    'string','...');

%%
D.InputTEXT = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.05,0.8,0.1,0.08],...
    'style','text',...
    'string',{'Input','Directory'},...
    'Fontsize',10);
D.InputEDIT = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.15,0.8,0.7,0.08],...
    'style','edit',...
    'string','NULL');
D.InputSel = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.86,0.8,0.09,0.08],...
    'style','pushbutton',...
    'string','...');
%%
D.COVTEXT = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.05,0.7,0.1,0.08],...
    'style','radiobutton',...
    'string','COV',...
    'Fontsize',10,...
    'value',1);
D.COVEDIT = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.15,0.7,0.7,0.08],...
    'style','edit',...
    'string','NULL');
D.COVSel = uicontrol('parent',D.fig,...
    'units','normalized',...
    'pos',[0.86,0.7,0.09,0.08],...
    'style','pushbutton',...
    'string','...');
%%
D.mask = uicontrol('parent',D.fig,...
    'units','norm',...
    'pos',[0.05,0.61,0.1,0.08],...
    'style','text',...
    'Fontsize',10,...
    'string','mask');
D.maskedit = uicontrol('parent',D.fig,...
    'units','norm',...
    'pos',[0.15,0.61,0.7,0.08],...
    'style','edit',...
    'string','Defaults');
D.masksel = uicontrol('parent',D.fig,...
    'units','norm',...
    'pos',[0.86,0.61,0.09,0.08],...
    'style','pushbutton',...
    'string','...');


D.Seedtype1 = uibuttongroup('parent',D.fig,...
    'units','norm',...
    'pos',[0.05,0.51,0.9,0.09]);
D.Seedtype2 = uibuttongroup('parent',D.fig,...
    'units','norm',...
    'pos',[0.05,0.42,0.9,0.09]);
D.Seedtype3 = uibuttongroup('parent',D.fig,...
    'units','norm',...
    'pos',[0.05,0.33,0.9,0.09]);
D.Seedtype4 = uibuttongroup('parent',D.fig,...
    'units','norm',...
    'pos',[0.05,0.24,0.9,0.09]);


D.seedtypes(1) = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.01,0.05,0.25,0.9],...
    'style','radiobutton',...
    'string','MNI',...
    'Fontsize',10,...
    'value',1);
D.seedtypes(2) = uicontrol('parent',D.Seedtype2,...
    'units','norm',...
    'pos',[0.01,0.05,0.25,0.9],...
    'style','radiobutton',...
    'string','Nifti Image ROIs',...
    'Fontsize',10,...
    'value',0);
D.seedtypes(3) = uicontrol('parent',D.Seedtype3,...
    'units','norm',...
    'pos',[0.01,0.05,0.25,0.9],...
    'style','radiobutton',...
    'string','Mat file(*.mat)',...
    'Fontsize',10,...
    'value',0);
D.seedtypes(4) = uicontrol('parent',D.Seedtype4,...
    'units','norm',...
    'pos',[0.01,0.05,0.25,0.9],...
    'style','radiobutton',...
    'string','Text File(*.txt)',...
    'Fontsize',10,...
    'value',0);

D.seedtype1_xtext = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.3,0.3,0.05,0.4],...
    'style','text',...
    'string','x = ');
D.seedtype1_xedit = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.35,0.3,0.1,0.4],...
    'style','edit');
D.seedtype1_ytext = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.45,0.3,0.05,0.4],...
    'style','text',...
    'string','y = ');
D.seedtype1_yedit = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.5,0.3,0.1,0.4],...
    'style','edit');
D.seedtype1_ztext = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.6,0.3,0.05,0.4],...
    'style','text',...
    'string','z = ');
D.seedtype1_zedit = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.65,0.3,0.1,0.4],...
    'style','edit');
D.seedtype1_radtext = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.75,0.3,0.1,0.4],...
    'style','text',...
    'string','rad(mm) = ');
D.seedtype1_radedit = uicontrol('parent',D.Seedtype1,...
    'units','norm',...
    'pos',[0.85,0.3,0.1,0.4],...
    'style','edit');

D.seedtype2_edit = uicontrol('parent',D.Seedtype2,...
    'units','norm',...
    'pos',[0.3,0.05,0.6,0.9],...
    'style','edit',...
    'string','NULL');
D.seedtype2_sel = uicontrol('parent',D.Seedtype2,...
    'units','norm',...
    'pos',[0.9,0.05,0.08,0.9],...
    'style','pushbutton',...
    'string','...',...
    'Tooltipstring','Select single ROI or multiple ROIs in one nifti file.');

D.seedtype3_edit = uicontrol('parent',D.Seedtype3,...
    'units','norm',...
    'pos',[0.3,0.05,0.4,0.9],...
    'style','edit',...
    'string','NULL');
D.seedtype3_sel = uicontrol('parent',D.Seedtype3,...
    'units','norm',...
    'pos',[0.7,0.05,0.08,0.9],...
    'style','pushbutton',...
    'string','...');
D.seedtype3_matname = uicontrol('parent',D.Seedtype3,...
    'units','norm',...
    'pos',[0.8,0.55,0.18,0.4],...
    'style','text',...
    'string','variable name');
D.seedtype3_matnameedit = uicontrol('parent',D.Seedtype3,...
    'units','norm',...
    'pos',[0.8,0.05,0.18,0.4],...
    'style','edit');

D.seedtype4_edit = uicontrol('parent',D.Seedtype4,...
    'units','norm',...
    'pos',[0.3,0.05,0.6,0.9],...
    'style','edit',...
    'string','NULL');
D.seedtype4_sel = uicontrol('parent',D.Seedtype4,...
    'units','norm',...
    'pos',[0.9,0.05,0.08,0.9],...
    'style','pushbutton',...
    'string','...');

set(D.seedtypes(2),'val',0);
set(D.seedtype2_edit,'enable','off');
set(D.seedtype2_sel,'enable','off');
set(D.seedtypes(3),'val',0);
set(D.seedtype3_edit,'enable','off');
set(D.seedtype3_sel,'enable','off');
set(D.seedtype3_matname,'enable','off');
set(D.seedtype3_matnameedit,'enable','off');
set(D.seedtypes(4),'val',0);
set(D.seedtype4_edit,'enable','off');
set(D.seedtype4_sel,'enable','off');

%%
D.OrderEdit = uibuttongroup('parent',D.fig,...
    'units','norm',...
    'pos',[0.05,0.15,0.9,0.09]);


D.ORD1 = uicontrol('parent',D.OrderEdit,...
    'units','norm',...
    'pos',[0.05,0.05,0.1,0.9],...
    'style','text',...
    'Fontsize',10,...
    'string',{'Image', 'Orders'});
D.ORDedit1 = uicontrol('parent',D.OrderEdit,...
    'units','norm',...
    'pos',[0.15,0.05,0.3,0.9],...
    'style','edit',...
    'string','Defaults');
D.ORDsel1 = uicontrol('parent',D.OrderEdit,...
    'units','norm',...
    'pos',[0.46,0.05,0.09,0.9],...
    'style','pushbutton',...
    'string','...');
D.calord = uicontrol('parent',D.OrderEdit,...
    'units','norm',...
    'pos',[0.56,0.05,0.09,0.9],...
    'style','text',...
    'string',{'GCA', 'order'});
D.calordedit = uicontrol('parent',D.OrderEdit,...
    'units','norm',...
    'pos',[0.66,0.05,0.09,0.9],...
    'style','edit',...
    'string','1');
D.Calmethod = uibuttongroup('parent',D.OrderEdit,...
    'units','norm',...
    'pos',[0.76 0.05 0.19 0.9]);
D.Calmethod1 = uicontrol('parent',D.Calmethod,...
    'units','norm',...
    'pos',[0.01,0.01,0.48,0.98],...
    'style','rad',...
    'string','residual');
D.Calmethod2 = uicontrol('parent',D.Calmethod,...
    'units','norm',...
    'pos',[0.51,0.01,0.48,0.98],...
    'style','rad',...
    'string','Coefficient');
set(D.Calmethod1,'val',1);
set(D.Calmethod2,'val',0);

set(D.ORDsel1,'callback',{@SelImgord_I,D});
%%

D.Comp = uicontrol('parent',D.fig,...
    'units','norm',...
    'pos',[0.4,0.05,0.25,0.08],...
    'style','pushbutton',...
    'string','Compute',...
    'Fontsize',10);
D.Exit = uicontrol('parent',D.fig,...
    'units','norm',...
    'pos',[0.7,0.05,0.25,0.08],...
    'style','pushbutton',...
    'string','Exit',...
    'Fontsize',10);

D.GlobalScale = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','rad',...
    'string','GlobalScale?',...
    'pos',[0.05,0.05,0.1,0.08],...
    'val',0);
D.perm  = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','rad',...
    'string','permutation',...
    'pos',[0.2,0.05,0.1,0.08],...
    'val',0);
D.permnum = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','edit',...
    'pos',[0.3,0.05,0.1,0.08],...
    'string','5000');
%
set(D.perm,'callback',{@Permwarn,D});
set(D.OutputSel,'callback',{@OutputSel,D});
set(D.InputSel,'callback',{@InputSel,D});
set(D.COVTEXT,'callback',{@COVselp,D});
set(D.COVSel,'callback',{@COVSel,D});
set(D.seedtypes(1),'callback',{@ChangeToMNI,D});
set(D.seedtypes(2),'callback',{@ChangeToROI,D});
set(D.seedtypes(3),'callback',{@ChangeToMAT,D});
set(D.seedtypes(4),'callback',{@ChangeToTEXT,D});
set(D.masksel,'callback',{@SelMASK,D});
set(D.seedtype2_sel,'callback',{@SelROI,D});
set(D.seedtype3_sel,'callback',{@Selmat,D});
set(D.seedtype4_sel,'callback',{@Seltext,D});
set(D.Comp,'callback',{@Compute,D});
set(D.Exit,'callback',{@Exit,D});
end
function Permwarn(varargin)
D = varargin{3};
uiwait(msgbox('Permutation would cost a lot of time'));

end
function SelMASK(varargin)
D = varargin{3};
[FileName,PathName,FilterIndex] = uigetfile({'*.nii';'*.img'},'maskfile selection');
PGseed = fullfile(PathName,FileName);
set(D.maskedit,'string',PGseed);
end
function Compute(varargin)
D = varargin{3};
cal_types = 'No';
if 0 % add in master version.
    cal_types = questdlg('Using ScatterOutlier?','ScatterOutlier','No');
end
Parameter.cal_types = cal_types;
Outputdir = get(D.OutputEDIT,'string');
if strcmp(Outputdir,'NULL')
    errordlg('Please Select Outputdir');
    error('Please Select Outputdir');
end
Parameter.Outputdir = Outputdir;
Inputdir = get(D.InputEDIT,'string');
if strcmp(Inputdir,'NULL')
    errordlg('Please Select Inputdir');
    error('Please Select Inputdir');
end
Parameter.Inputdir = Inputdir;
masks = get(D.maskedit,'string');
Parameter.masks = masks;
covs = get(D.COVTEXT,'val');
Parameter.covs = covs;
if covs==1
    COVtext = get(D.COVEDIT,'string');
    if strcmp(COVtext,'NULL');
        errordlg('Please select covariate text file');
        error('Please select covariate text file');
    end
    Parameter.COVtext = COVtext;
else
    Parameter.COVtext = '';
end

Seedtype = get(D.seedtypes,'val');
if Seedtype{1}
    Parameter.SeedROItype = 1;
    tempv1 = get(D.seedtype1_xedit,'string');
    mni(1) = str2num(tempv1);
    tempv2 = get(D.seedtype1_yedit,'string');
    mni(2) = str2num(tempv2);
    tempv3 = get(D.seedtype1_zedit,'string');
    mni(3) = str2num(tempv3);
    tempr = get(D.seedtype1_radedit,'string');
    radius = str2num(tempr);
    Parameter.SeedROI_mni = mni;
    Parameter.SeedROI_radius = radius;
elseif Seedtype{2}
    Parameter.SeedROItype = 2;
    roipath = get(D.seedtype2_edit,'string');
    Parameter.SeedROI_nifti = roipath;
elseif Seedtype{3}
    Parameter.SeedROItype = 3;
    matpath = get(D.seedtype3_edit,'string');
    Parameter.SeedROI_mat = matpath;
    varnam = get(D.seedtype3_matnameedit,'string');
    Parameter.SeedROI_varname = varnam;
else
    Parameter.SeedROItype = 4;
    txtpath = get(D.seedtype4_edit,'string');
    Parameter.SeedROI_txt = txtpath;
end
Parameter.GlobalScal = get(D.GlobalScale,'val');
Parameter.imageorder = get(D.ORDedit1,'string');
Parameter.GCAorder = str2num(get(D.calordedit,'string'));
Parameter.Calmethod1 = get(D.Calmethod1,'val');

Parameter.perm = get(D.perm,'val');
Parameter.permnum = str2num(get(D.permnum,'string'));

outputmat = fullfile(Outputdir,'SetUpparameter.mat');
save(outputmat,'Parameter');
disp('Now calculating');
BCCT_CaSCN_computemain(Parameter)
uiwait(msgbox('Finished!'));
disp('Finished!');
end
function SelROI(varargin)
D = varargin{3};
[FileName,PathName,FilterIndex] = uigetfile({'*.nii';'*.img'},'SeedROI selection');
PGseed = fullfile(PathName,FileName);
set(D.seedtype2_edit,'string',PGseed);
end
function Selmat(varargin)
D = varargin{3};
[FileName,PathName,FilterIndex] = uigetfile({'*.mat'},'mat file selection');
PGseed = fullfile(PathName,FileName);
set(D.seedtype3_edit,'string',PGseed);
end
function Seltext(varargin)
D = varargin{3};
[FileName,PathName,FilterIndex] = uigetfile({'*.txt'},'mat file selection');
PGseed = fullfile(PathName,FileName);
set(D.seedtype4_edit,'string',PGseed);
end
function ChangeToMNI(varargin)
D = varargin{3};
set(D.seedtypes(1),'val',1);
set(D.seedtype1_xtext,'enable','on');
set(D.seedtype1_xedit,'enable','on');
set(D.seedtype1_ytext,'enable','on');
set(D.seedtype1_yedit,'enable','on');
set(D.seedtype1_ztext,'enable','on');
set(D.seedtype1_zedit,'enable','on');
set(D.seedtype1_radtext,'enable','on');
set(D.seedtype1_radedit,'enable','on');
set(D.seedtypes(2),'val',0);
set(D.seedtype2_edit,'enable','off');
set(D.seedtype2_sel,'enable','off');
set(D.seedtypes(3),'val',0);
set(D.seedtype3_edit,'enable','off');
set(D.seedtype3_sel,'enable','off');
set(D.seedtype3_matname,'enable','off');
set(D.seedtype3_matnameedit,'enable','off');
set(D.seedtypes(4),'val',0);
set(D.seedtype4_edit,'enable','off');
set(D.seedtype4_sel,'enable','off');
end
function ChangeToROI(varargin)
D = varargin{3};
set(D.seedtypes(1),'val',0);
set(D.seedtype1_xtext,'enable','off');
set(D.seedtype1_xedit,'enable','off');
set(D.seedtype1_ytext,'enable','off');
set(D.seedtype1_yedit,'enable','off');
set(D.seedtype1_ztext,'enable','off');
set(D.seedtype1_zedit,'enable','off');
set(D.seedtype1_radtext,'enable','off');
set(D.seedtype1_radedit,'enable','off');
set(D.seedtypes(2),'val',1);
set(D.seedtype2_edit,'enable','on');
set(D.seedtype2_sel,'enable','on');
set(D.seedtypes(3),'val',0);
set(D.seedtype3_edit,'enable','off');
set(D.seedtype3_sel,'enable','off');
set(D.seedtype3_matname,'enable','off');
set(D.seedtype3_matnameedit,'enable','off');
set(D.seedtypes(4),'val',0);
set(D.seedtype4_edit,'enable','off');
set(D.seedtype4_sel,'enable','off');
end
function ChangeToMAT(varargin)
D = varargin{3};
set(D.seedtypes(1),'val',0);
set(D.seedtype1_xtext,'enable','off');
set(D.seedtype1_xedit,'enable','off');
set(D.seedtype1_ytext,'enable','off');
set(D.seedtype1_yedit,'enable','off');
set(D.seedtype1_ztext,'enable','off');
set(D.seedtype1_zedit,'enable','off');
set(D.seedtype1_radtext,'enable','off');
set(D.seedtype1_radedit,'enable','off');
set(D.seedtypes(2),'val',0);
set(D.seedtype2_edit,'enable','off');
set(D.seedtype2_sel,'enable','off');
set(D.seedtypes(3),'val',1);
set(D.seedtype3_edit,'enable','on');
set(D.seedtype3_sel,'enable','on');
set(D.seedtype3_matname,'enable','on');
set(D.seedtype3_matnameedit,'enable','on');
set(D.seedtypes(4),'val',0);
set(D.seedtype4_edit,'enable','off');
set(D.seedtype4_sel,'enable','off');
end
function ChangeToTEXT(varargin)
D = varargin{3};
set(D.seedtypes(1),'val',0);
set(D.seedtype1_xtext,'enable','off');
set(D.seedtype1_xedit,'enable','off');
set(D.seedtype1_ytext,'enable','off');
set(D.seedtype1_yedit,'enable','off');
set(D.seedtype1_ztext,'enable','off');
set(D.seedtype1_zedit,'enable','off');
set(D.seedtype1_radtext,'enable','off');
set(D.seedtype1_radedit,'enable','off');
set(D.seedtypes(2),'val',0);
set(D.seedtype2_edit,'enable','off');
set(D.seedtype2_sel,'enable','off');
set(D.seedtypes(3),'val',0);
set(D.seedtype3_edit,'enable','off');
set(D.seedtype3_sel,'enable','off');
set(D.seedtype3_matname,'enable','off');
set(D.seedtype3_matnameedit,'enable','off');
set(D.seedtypes(4),'val',1);
set(D.seedtype4_edit,'enable','on');
set(D.seedtype4_sel,'enable','on');
end
function Exit(varargin)
D = varargin{3};
close(D.fig);
BCCT_CaSCN_GUI;
end
function OutputSel(varargin)
D = varargin{3};
PG = uigetdir(pwd,'Output Directory Selection');
set(D.OutputEDIT,'string',PG)
end
function InputSel(varargin)
D = varargin{3};
PG = uigetdir(pwd,'Input Directory Selection');
set(D.InputEDIT,'string',PG)
end
function COVselp(varargin)
D = varargin{3};
val = get(D.COVTEXT,'value');
if val==1
    set(D.COVSel,'Enable','on');
    set(D.COVEDIT,'Enable','on');
else
    set(D.COVSel,'Enable','off');
    set(D.COVEDIT,'Enable','off');
end
end
function COVSel(varargin)
D = varargin{3};
[FileName,PathName,FilterIndex] = uigetfile('*.txt','COVtext selection');
PGtxt = fullfile(PathName,FileName);
set(D.COVEDIT,'string',PGtxt);
end

function SelImgord_I(varargin)
D = varargin{3};

[FileName,PathName,FilterIndex] = uigetfile({'*.txt'},'image orders');
PGseed = fullfile(PathName,FileName);
set(D.ORDedit1,'string',PGseed);
end