function BCCT_WTA_GUI
D.fig = figure('Name','Brain Covariance Connectivity Cor2SubCor&Winner Take All',...       
    'units','normalized',...      
    'menubar','none',...       
    'numbertitle','off',...      
    'color',[0.95 0.95 0.95],...
    'position',[0.3 0.3 0.4 0.4]);
movegui(D.fig,'center'); 
D.title1 = uicontrol('parent',D.fig,...
    'units','normalized',...
    'style','Text',...
    'pos',[0.1,0.85,0.8,0.1],...
    'string','Across Subject Connectivity: Cortex-SubCortex');
D.title2 = uicontrol('parent',D.fig,...
    'units','normalized',...
    'style','Text',...
    'pos',[0.1,0.75,0.8,0.1],...
    'string','Winner-Take-All(WTA)');
D.SetUp = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','pushbutton',...
    'pos',[0.25,0.5,0.2,0.2],...
    'string','Setup&Calculate');
D.Showres = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','pushbutton',...
    'pos',[0.55,0.5,0.2,0.2],...
    'string','Show Pattern and Radar');
D.Stat = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','pushbutton',...
    'pos',[0.25,0.2,0.2,0.2],...
    'string','Statistcal Analysis(Two groups)');
D.Utils = uicontrol('parent',D.fig,...
    'units','norm',...
    'pos',[0.55,0.3,0.2,0.08],...
    'style','popupmenu',...
    'string','Utilites');
D.Exit = uicontrol('parent',D.fig,...
    'units','norm',...
    'style','pushbutton',...
    'pos',[0.55,0.2,0.2,0.08],...
    'string','Exit');
set(D.Exit,'callback',{@ASWTAExit,D});
set(D.Utils,'callback',{@ASWTAutil,D});
set(D.Stat,'callback',{@ASWTAStat,D});
set(D.Showres,'callback',{@ASWTAshowres,D});
set(D.SetUp,'callback',{@ASWTAsetup,D});
end
function ASWTAExit(varargin)
D = varargin{3};
close(D.fig);
BCCT;
end
function ASWTAutil(varargin)
D = varargin{3};
uiwait(msgbox('Comming soon'));
end
function ASWTAsetup(varargin)
D = varargin{3};
close(D.fig);
BCCT_WTA_SetupCal;
end
function ASWTAshowres(varargin)
D = varargin{3};
close(D.fig);
BCCT_ShowWTAGUI;
end
function ASWTAStat(varargin)
D = varargin{3};
close(D.fig);
BCCT_WTA_statGUI;
end