function BCCT_WTA_statGUI
W.fig = figure('Name','WTA_stat_GUI',...       
    'units','normalized',...      
    'menubar','none',...       
    'numbertitle','off',...      
    'color',[0.95 0.95 0.95],...
    'position',[0.20 0.15 0.5 0.5]);
movegui(W.fig,'center'); 

W.OutputText = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.05,0.8,0.1,0.08],...
    'style','text',...
    'string',{'Output','Directory'},...
    'Fontsize',10);
W.OutputEDIT = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.15,0.8,0.7,0.08],...
    'style','edit',...
    'string','NULL');
W.OutputSel = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.86,0.8,0.09,0.08],...
    'style','pushbutton',...
    'string','...');
%%

W.Input1Text = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.05,0.65,0.1,0.08],...
    'style','text',...
    'string',{'Group 1 Input','Directory'},...
    'Fontsize',10);
W.Input1EDIT = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.15,0.65,0.7,0.08],...
    'style','edit',...
    'string','NULL');
W.Input1Sel = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.86,0.65,0.09,0.08],...
    'style','pushbutton',...
    'string','...');


W.Input2Text = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.05,0.5,0.1,0.08],...
    'style','text',...
    'string',{'Group 2 Input','Directory'},...
    'Fontsize',10);
W.Input2EDIT = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.15,0.5,0.7,0.08],...
    'style','edit',...
    'string','NULL');
W.Input2Sel = uicontrol('parent',W.fig,...
    'units','normalized',...
    'pos',[0.86,0.5,0.09,0.08],...
    'style','pushbutton',...
    'string','...');

%%
W.STtype1 = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.1,0.3,0.1,0.08],...
    'style','rad',...
    'string','Permutation');
W.STtype2 = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.6,0.3,0.1,0.08],...
    'style','rad',...
    'string','Interaction');
W.STpermtext = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.27,0.3,0.1,0.08],...
    'style','text',...
    'string',{'Permutation', 'times'});
W.STpermedit = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.35,0.3,0.1,0.08],...
    'style','edit',...
    'string','5000');

W.cal = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.15,0.1,0.2,0.08],...
    'style','pushbutton',...
    'string','Calculate');
W.res = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.4,0.1,0.2,0.08],...
    'style','pushbutton',...
    'string','reset');
W.exit = uicontrol('parent',W.fig,...
    'units','norm',...
    'pos',[0.65,0.1,0.2,0.08],...
    'style','pushbutton',...
    'string','exit');
set(W.STtype1,'val',1);
set(W.STtype2,'val',0);
set(W.STpermedit,'enable','on');
set(W.STpermtext,'enable','on');
%%
% the interaction comp will add in master version.
set(W.STtype2,'enable','off');
% 
set(W.Input1Sel,'callback',{@ASWTA_input1,W});
set(W.Input2Sel,'callback',{@ASWTA_input2,W});
set(W.OutputSel,'callback',{@ASWTA_output,W});
set(W.STtype1,'callback',{@ASWTA_sttype1,W});
set(W.STtype2,'callback',{@ASWTA_sttype2,W});
set(W.cal,'callback',{@ASWTA_calcu,W});
set(W.res,'callback',{@ASWTA_reset,W});
set(W.exit,'callback',{@ASWTA_exit,W});

end
function ASWTA_output(varargin)
W = varargin{3};
PG = uigetdir(pwd,'Output Directory Selection');
set(W.OutputEDIT,'string',PG)
end
function ASWTA_input1(varargin)
W = varargin{3};
PG = uigetdir(pwd,'Group1 Input Directory Selection');
set(W.Input1EDIT,'string',PG)
end
function ASWTA_input2(varargin)
W = varargin{3};
PG = uigetdir(pwd,'Group2 Input Directory Selection');
set(W.Input2EDIT,'string',PG)
end
function ASWTA_sttype1(varargin)
W = varargin{3};
set(W.STtype1,'val',1);
set(W.STtype2,'val',0);
set(W.STpermedit,'enable','on');
set(W.STpermtext,'enable','on');
end
function ASWTA_sttype2(varargin)
W = varargin{3};
set(W.STtype2,'val',1);
set(W.STtype1,'val',0);
set(W.STpermedit,'enable','off');
set(W.STpermtext,'enable','off');
end
function ASWTA_calcu(varargin)
W = varargin{3};
Outdir = get(W.OutputEDIT,'string');
Input1 = get(W.Input1EDIT,'string');
Input2 = get(W.Input2EDIT,'string');
if strcmp(Outdir,'NULL')||strcmp(Outdir,'0')
    error('wrong outputdir');
end
if strcmp(Input1,'NULL')||strcmp(Input1,'0')
    error('wrong group1 indir');
end
if strcmp(Input2,'NULL')||strcmp(Input2,'0')
    error('wrong group2 indir');
end
permtype = get(W.STtype1,'val');
if permtype==1
    permnum = str2num(get(W.STpermedit,'string'));
else
    permnum = 0;
end
Parameter.Outdir = Outdir;
Parameter.Input1 = Input1;
Parameter.Input2 = Input2;
Parameter.permtype = permtype;
Parameter.permnum = permnum;
save(fullfile(Outdir,'SetUpparameter.mat'),'Parameter');
BCCT_WTA_Stat_main_ver2(Parameter);
end
function ASWTA_reset(varargin)
W = varargin{3};
close(W.fig)
BCCT_WTA_statGUI;
end
function ASWTA_exit(varargin)
W = varargin{3};
close(W.fig);
BCCT_WTA_GUI;
end