function BCCT_MOD_Surf_GUI
D.fig = figure('unit','norm',...
    'pos',[0.4,0.4,0.2,0.2],...
    'name','Modulate effect of Structural Covariance Surface-based Map',...
    'menubar','none');
D.Freesurfer = uicontrol('parent',D.fig,...
    'unit','norm',...
    'pos',[0.1,0.3,0.3,0.4],...
    'style','pushbutton',...
    'string','FreeSurfer Standard');
D.Other = uicontrol('parent',D.fig,...
    'unit','norm',...
    'pos',[0.6,0.3,0.3,0.4],...
    'style','pushbutton',...
    'string','Other type (*.gii et al.)');
D.exit = uicontrol('parent',D.fig,...
    'unit','norm',...
    'pos',[0.8,0.05,0.1,0.1],...
    'style','pushbutton',...
    'string','Exit');
set(D.Freesurfer,'callback',{@FREESURFERBASED,D})
set(D.Other,'callback',{@OTHERMOD,D})
set(D.exit,'callback',{@Exit,D})
end
function FREESURFERBASED(varargin)
D = varargin{3};
close(D.fig);
BCCT_MOD_Surf_GUI_freesurfer;
end
function OTHERMOD(varargin)
D = varargin{3};
uiwait(msgbox('Only Support the standard freesurfer files(*.mgh), *.gii is comming soon'));
end
function Exit(varargin)
D = varargin{3};
close(D.fig);
BCCT_Modulate_GUI;
end